### PR TITLE
feat: add edit links

### PR DESCRIPTION
**Pull request by Gagaro**
Add edit links in the table to be able to edit the content directly.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Good idea. A couple of comments:

- On Plone 4, the icon does not show up, only the 'edit' link.
- It is probably nicer to only show the icon, and have the `edit` text only as an alt text or a title tooltip.
- I find it strange that the edit link only shows up when the form is called with a folder as context, because of the `isFolderish` condition. Well, that condition does not make sense at all to me: we should show the path column always. But that is outside of the scope of this pull request.

**Comment by mauritsvanrees** [comment]
To fix the possible merge conflict in `CHANGES.rst` after merging all the other pull requests, I rebased your pull request on master. The comments from my first remark are open for fixing.
Thanks for your work! These are all nice and handy additions.

**Comment by Gagaro** [comment]
Thanks for all the reviews. I'll take a look to fix what's left for this PR.

**Comment by Gagaro** [comment]
> I find it strange that the edit link only shows up when the form is called with a folder as context, because of the isFolderish condition. Well, that condition does not make sense at all to me: we should show the path column always. But that is outside of the scope of this pull request.

When you are not in a folder, you are on the context being searched already. So there is no really sense in showing the path there, or the edit link, as it should already be shown in the action bar.

**Comment by mauritsvanrees** [comment]
> When you are not in a folder, you are on the context being searched already. So there is no really sense in showing the path there, or the edit link, as it should already be shown in the action bar.

Ah, true. I think I want to change the tab to point to the folder so you don't get this 'problem' by default, but that is a separate issue.
I'll merge this one.

**Pull request merged**
