### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by gotcha**
I need to extend the search and replace to `IStringField` fields.

I thought the current code was quite difficult to read/understand so I refactored it prior to extending functionality.

I added tests for the `update_modified` setting that was missing tests.

Icing on the cake: 5.2 on Py3 support and Travis setup

### CODE REVIEW

**Comment by gotcha** [comment]
Tests pass for 4.3 and 5.1.

**Comment by gotcha** [comment]
Tests pass also for 5.2 with both Py2 and 3

**Comment by gotcha** [comment]
@cillianderoiste I see you worked on python3 branch. Would you mind reviewing what I did ?

**Comment by gotcha** [comment]
@mauritsvanrees Thanks for merging !

I will fix `plone.api`usage.

Thanks for the "breaking" release.

Am I correct that coveralls is fixed. What did you do ?

**Comment by mauritsvanrees** [comment]
No, coveralls is still broken. See https://travis-ci.org/collective/collective.searchandreplace/jobs/647388939#L1518

**Pull request merged**
