### PR TITLE
set up GitHub Actions including Plone 6

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by spereverde** [comment]
The broken import for Plone 6 was fixed by cf438c22707df1d6cd7266c273d454378432d900
So it makes sense that this now works
Maybe we should make a release so there is a version that is PLone 6 compatble?

**Review by mauritsvanrees — APPROVED** [review]
For me it would be fine to drop Python 2.7 support.  And I would not have gone with five gh-actions files.  But it works, so I am happy.  Thanks!

**Comment by mauritsvanrees** [comment]
I have released 8.2.2 with this.

**Comment by spereverde** [comment]
Thanks all!

**Pull request merged**
